package objects.items;

public enum TypeMateriaux {
    MORCEAU_DE_PIERRE, PEAU, CUIR, CORNE, COEUR_DE_GOLEM, GEMME, ORBE_DE_FEU, ORBE_DE_GLACE, ORBE_DE_TENEBRE, ORBE_DE_TERRE,
    ORBE_DE_LUMIERE, ORBE_D_EAU, ORBE_DE_FOUDRE, ORBE_DE_VENT, SERRE, ECAILLE;

}
